algoritmo "Procedimento - Somar"


procedimento somar(a, b: inteiro)
var
   resultado: inteiro
inicio

   resultado <- a + b

   escreval("Soma ", resultado )
   escreval

fimprocedimento


var

   num1, num2: inteiro

inicio

   escreva("Digite um número: ")
   leia(num1)
   escreva("Digite outro número: ")
   leia(num2)

   somar(3,7)
   somar(num1, num2)


fimalgoritmo